### ISSUE TITLE
How to minimize cost per km along with total distance?

### ISSUE THREAD

**Issue by Midhilesh29** [Mapotempo/optimizer-ortools#1]
I have given the information about the cost per km for each vehicle. My objective is to minimize the distance along with the cost by choosing optimal vehicles. I am using google or-tools where the objective function is to minimize the total distance. Is there any way to incorporate the cost per km information and minimize that along with total distance using google or-tools in python language?

**Comment by braktar** [comment]
Hello,

We only propose a custom routing model through Protobuf to use OR-tools in C++. For any question about OR-Tools, particularly in python, you can use the discussion group: https://groups.google.com/forum/#!forum/or-tools-discuss
